import React, { useState } from "react";
import { useForm, useWatch, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useLocation } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import { Loader2, ArrowRight, ArrowLeft, ExternalLink, Sparkles, Wand2, X } from "lucide-react";
import { Link } from "wouter";

import {
  AssessmentSchema,
  AssessmentData,
  ContactChannel,
  IndustrySchema
} from "@/lib/types";
import {
  STEPS,
  REVENUE_PAIN_OPTIONS,
  TEAM_SIZE_OPTIONS,
  MONTHLY_LEAD_VOLUME_OPTIONS,
  FIRST_CONTACT_SPEED_OPTIONS,
  LEAD_UNAVAILABILITY_OPTIONS,
  PHONE_UNAVAILABLE_HANDLING_OPTIONS,
  DIGITAL_UNAVAILABLE_HANDLING_OPTIONS,
  NO_SHOW_RECOVERY_OPTIONS,
  QUOTE_FOLLOWUP_OPTIONS,
  DORMANT_LEADS_OPTIONS,
  NO_SHOW_RATE_OPTIONS,
  CONTACT_CHANNEL_OPTIONS,
  AI_SEARCH_FREQUENCY_OPTIONS,
  AI_READINESS_OPTIONS,
  HAS_AUTOMATIONS_OPTIONS,
  HAS_AI_INTENT_OPTIONS,
  STAFF_REPEAT_QUESTIONS_OPTIONS,
  PROCESS_DOCUMENTATION_OPTIONS,
  INTAKE_CENTRALIZATION_OPTIONS,
  PIPELINE_TRACKING_OPTIONS,
  REVIEW_REQUEST_OPTIONS,
  CLOSE_RATE_OPTIONS,
  MANUAL_HOURS_OPTIONS,
  OPERATIONAL_COMPLEXITY_OPTIONS,
  INDUSTRY_NICHE_MAP,
  resolveIndustryConfig,
} from "@/lib/constants";
import { calculateResults, AssessmentResult } from "@/lib/scoring";
import {
  GlassButton,
  GlassCard,
  GlassInput,
  GlassLabel,
  GlassSlider,
  GlassRadioGroup,
  VisualCardSelector
} from "@/components/ui/glass-ui";
import { useWebsiteScrape } from "@/hooks/use-website-scrape";
import { useSpecialization } from "@/hooks/use-specialization";
import { ScrapeInsightPanel } from "@/components/ScrapeInsightPanel";

// Specialization is now generated by Claude AI via useSpecialization hook.
// No static matching needed — each business gets a custom label.

// getJobValueConfig replaced by resolveIndustryConfig from constants.ts

export default function Assessment() {
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [, setLocation] = useLocation();

  const {
    register,
    control,
    handleSubmit,
    trigger,
    setValue,
    getValues,
    formState: { errors }
  } = useForm<AssessmentData>({
    resolver: zodResolver(AssessmentSchema),
    mode: "onChange",
    defaultValues: {
      revenue_pain: [],
      contact_channels: [],
      disclaimer_accepted: false,
      contact_phone: "",
    }
  });

  const watchedValues = useWatch({ control });
  const currentStep = STEPS[currentStepIndex];

  // Trigger Firecrawl scrape when user enters their website URL.
  // Auto-applies business name + industry when detected (only if fields are empty).
  const {
    insights: scrapeInsights,
    status: scrapeStatus,
    dismiss: dismissScrape,
  } = useWebsiteScrape(watchedValues.website_url);

  // AI-powered NAICS classification. Returns industry label (NAICS-aligned) +
  // 6-digit code + official title + a 2–6 word specialization from the scraped
  // context, OR just specialization from manual inputs. Single source of truth.
  const {
    suggestion: specSuggestion,
    suggestedIndustry,
    suggestedNaicsCode,
    suggestedNaicsTitle,
    suggestedBusinessName,
    status: specStatus,
    showFallback: showSpecFallback,
    generateFromManual: generateSpecFromManual,
    dismiss: dismissSpec,
  } = useSpecialization(
    watchedValues.industry,
    scrapeInsights,
    scrapeStatus,
    watchedValues.website_url
  );

  // State for the manual fallback inputs (shown when no URL / scrape failed)
  const [manualSpecialty, setManualSpecialty] = useState("");
  const [manualCustomer, setManualCustomer] = useState("");
  const [showManualForm, setShowManualForm] = useState(false);

  // State for industry dropdown suggestions
  const [showIndustrySuggestions, setShowIndustrySuggestions] = useState(false);
  const [industryFilter, setIndustryFilter] = useState("");

  // Auto-fill business name the moment scrape completes (only if field is empty)
  React.useEffect(() => {
    if (scrapeStatus !== 'success' || !scrapeInsights?.success) return;
    if (scrapeInsights.businessName && !watchedValues.business_name) {
      setValue('business_name', scrapeInsights.businessName, { shouldValidate: true, shouldDirty: true });
    }
  }, [scrapeStatus, scrapeInsights]);

  // Auto-apply Claude-classified industry + specialization + corrected business name.
  // Claude is authoritative — it corrects the scraper when the domain is a geo/SEO name
  // (e.g. landscapingboise.com → scraper: "Landscaping Boise", Claude: "Chamberlain & Sons").
  React.useEffect(() => {
    if (specStatus !== 'suggested') return;

    if (suggestedIndustry && !watchedValues.industry) {
      const parsed = IndustrySchema.safeParse(suggestedIndustry);
      if (parsed.success) {
        setValue('industry', parsed.data, { shouldValidate: true, shouldDirty: true });
      }
    }

    if (specSuggestion && !watchedValues.niche_specificity) {
      setValue('niche_specificity', specSuggestion, { shouldValidate: true, shouldDirty: true });
    }

    // Apply Claude's corrected business name if the scraper got it wrong.
    // Only override if the current value matches the domain-derived scraper value
    // (i.e. the user hasn't manually typed something different).
    if (suggestedBusinessName) {
      const current = watchedValues.business_name;
      const scraperName = scrapeInsights?.businessName;
      // Override if: field is empty OR still showing the scraper's (potentially wrong) value
      if (!current || current === scraperName) {
        setValue('business_name', suggestedBusinessName, { shouldValidate: true, shouldDirty: true });
      }
    }
  }, [specStatus, specSuggestion, suggestedIndustry, suggestedBusinessName]);

  const isStep3 = currentStep.id === 'pain';

  const handlePainToggle = (value: string) => {
    const currentPains = (watchedValues.revenue_pain || []) as { value: string; severity: number }[];
    const existingIndex = currentPains.findIndex(p => p.value === value);
    
    if (existingIndex >= 0) {
      setValue('revenue_pain', currentPains.filter(p => p.value !== value));
    } else {
      setValue('revenue_pain', [...currentPains, { value, severity: 3 }]);
    }
  };

  const handleChannelToggle = (channel: ContactChannel) => {
    const current = watchedValues.contact_channels || [];
    if (current.includes(channel)) {
      setValue('contact_channels', current.filter(c => c !== channel));
    } else {
      setValue('contact_channels', [...current, channel]);
    }
  };

  const handleNext = async () => {
    const fieldsToValidate = currentStep.fields as (keyof AssessmentData)[];
    const isValid = await trigger(fieldsToValidate);
    
    if (!isValid) return;

    if (currentStepIndex === STEPS.length - 1) {
      setIsSubmitting(true);
      const data = getValues();
      
      try {
        const result = calculateResults(data);
        
        const response = await fetch('/api/assessment/submit', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            assessmentData: data,
            contactFirstName: data.contact_first_name,
            contactLastName: data.contact_last_name,
            contactEmail: data.contact_email,
            contactPhone: data.contact_phone || '',
          }),
        });
        
        const responseData = await response.json();
        
        sessionStorage.setItem('assessmentResult', JSON.stringify(result));
        sessionStorage.setItem('leadId', responseData.leadId || '');
        sessionStorage.setItem('contactEmail', data.contact_email || '');
        
        setLocation('/results');
      } catch (error) {
        console.error('Error submitting assessment:', error);
      } finally {
        setIsSubmitting(false);
      }
      return;
    }

    setCurrentStepIndex(prev => Math.min(prev + 1, STEPS.length - 1));
  };

  const handleBack = () => {
    setCurrentStepIndex(prev => Math.max(prev - 1, 0));
  };

  const renderField = (field: string) => {
    switch (field) {
      case 'revenue_pain':
        return (
          <div className="space-y-4 w-full">
            <div className="flex justify-between items-center">
              <span className="text-sm text-slate-500">{(watchedValues.revenue_pain || []).length} selected</span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {REVENUE_PAIN_OPTIONS.map(option => {
                const isSelected = (watchedValues.revenue_pain || []).some(p => p.value === option.value);
                return (
                  <button
                    key={option.value}
                    type="button"
                    onClick={() => handlePainToggle(option.value)}
                    className={`flex flex-col p-4 rounded-xl border text-left transition-all ${
                      isSelected 
                        ? 'bg-[#0d1a1f] border-[#00D9FF]/60 shadow-[0_0_20px_rgba(0,217,255,0.2)]' 
                        : 'bg-[#12161a] border-[#2a3038] hover:bg-[#181d22] hover:border-[#3a4048]'
                    }`}
                    data-testid={`button-pain-${option.value.toLowerCase().replace(/\s+/g, '-')}`}
                  >
                    <span className={`font-medium ${isSelected ? 'text-white' : 'text-[#c0c8d0]'}`}>{option.value}</span>
                    <span className="text-sm text-[#6b7280] mt-1">{option.subtitle}</span>
                  </button>
                );
              })}
            </div>
            {errors.revenue_pain && <p className="text-cyan-400 text-xs">{errors.revenue_pain.message}</p>}
          </div>
        );

      case 'website_url':
        return (
          <div className="space-y-2 w-full">
            <GlassLabel htmlFor="website_url">Website URL</GlassLabel>
            <GlassInput
              id="website_url"
              placeholder="e.g. https://acme.com"
              {...register('website_url')}
              data-testid="input-website-url"
            />
            {errors.website_url && <p className="text-cyan-400 text-xs">{errors.website_url.message}</p>}
            <ScrapeInsightPanel
              status={scrapeStatus}
              insights={scrapeInsights}
              currentBusinessName={watchedValues.business_name}
              currentIndustry={watchedValues.industry}
              currentSpecialization={watchedValues.niche_specificity}
              specSuggestion={specSuggestion}
              suggestedIndustry={suggestedIndustry}
              suggestedBusinessName={suggestedBusinessName}
              suggestedNaicsCode={suggestedNaicsCode}
              suggestedNaicsTitle={suggestedNaicsTitle}
              specStatus={specStatus}
              onApplyBusinessName={(name) =>
                setValue('business_name', name, { shouldValidate: true, shouldDirty: true })
              }
              onApplyIndustry={(industry) => {
                const parsed = IndustrySchema.safeParse(industry);
                if (!parsed.success) return;
                setValue('industry', parsed.data, { shouldValidate: true, shouldDirty: true });
                setValue('niche_specificity', '');
              }}
              onApplySpecialization={(spec) =>
                setValue('niche_specificity', spec, { shouldValidate: true, shouldDirty: true })
              }
              onDismiss={dismissScrape}
            />
          </div>
        );

      case 'business_name':
        return (
          <div className="space-y-2 w-full">
            <GlassLabel htmlFor="business_name">Company Name</GlassLabel>
            <GlassInput
              id="business_name"
              placeholder="e.g. Acme Services"
              {...register('business_name')}
              data-testid="input-business-name"
            />
            {errors.business_name && <p className="text-cyan-400 text-xs">{errors.business_name.message}</p>}
          </div>
        );

      case 'industry': {
        // Free-text industry field with smart suggestions. Claude classifies to a NAICS-aligned label
        // (e.g. "Specialty Trade Contractor", "Offices of Dentists", "Med Spa").
        // Dropdown shows relevant industries based on scraped hints or user input.
        const showNaics = !!suggestedNaicsCode && watchedValues.industry === suggestedIndustry;

        // Get all available industries from INDUSTRY_NICHE_MAP
        const allIndustries = Object.keys(INDUSTRY_NICHE_MAP);

        // Smart filtering: prioritize scraped hints, then filter by typed input
        const getFilteredSuggestions = () => {
          const currentInput = watchedValues.industry?.toLowerCase() || '';

          // If scrape hints exist, show them first, otherwise show all industries
          let suggested = (scrapeInsights?.success && scrapeInsights.industryHints && scrapeInsights.industryHints.length > 0)
            ? scrapeInsights.industryHints
            : allIndustries;

          // Filter by current input if user is typing
          if (currentInput.trim()) {
            suggested = suggested.filter(ind =>
              ind.toLowerCase().includes(currentInput)
            );
          }

          return suggested.slice(0, 8); // Limit to 8 suggestions
        };

        const filteredIndustries = getFilteredSuggestions();
        const shouldShowSuggestions = showIndustrySuggestions && filteredIndustries.length > 0;

        return (
          <div className="space-y-2 w-full">
            <div className="flex items-center justify-between">
              <GlassLabel htmlFor="industry">Industry</GlassLabel>
              {showNaics && (
                <span
                  className="text-[10px] font-mono tracking-wide text-cyan-300/70"
                  title={suggestedNaicsTitle ?? undefined}
                  data-testid="industry-naics-badge"
                >
                  NAICS {suggestedNaicsCode}
                </span>
              )}
            </div>

            {/* Industry input with dropdown trigger */}
            <div className="relative">
              <GlassInput
                id="industry"
                placeholder="e.g. Roofing Contractor, Med Spa, Law Firm"
                value={watchedValues.industry || ''}
                onChange={(e) => {
                  setValue('industry', e.target.value);
                  // Clear specialization when user manually overrides industry
                  if (watchedValues.niche_specificity) {
                    setValue('niche_specificity', '');
                  }
                  setShowIndustrySuggestions(true);
                }}
                onFocus={() => setShowIndustrySuggestions(true)}
                onBlur={() => setTimeout(() => setShowIndustrySuggestions(false), 200)}
                data-testid="input-industry"
              />

              {/* Dropdown suggestions */}
              {shouldShowSuggestions && (
                <motion.div
                  initial={{ opacity: 0, y: -8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  className="absolute top-full left-0 right-0 mt-1 bg-[#0f1419] border border-cyan-500/30 rounded-xl shadow-2xl overflow-hidden z-50"
                  data-testid="industry-suggestions-dropdown"
                >
                  {filteredIndustries.map((industry) => (
                    <button
                      key={industry}
                      type="button"
                      onClick={() => {
                        setValue('industry', industry, { shouldValidate: true, shouldDirty: true });
                        setShowIndustrySuggestions(false);
                      }}
                      className={`w-full px-4 py-3 text-left text-sm transition-colors ${
                        watchedValues.industry === industry
                          ? 'bg-cyan-500/20 text-cyan-300'
                          : 'text-slate-300 hover:bg-cyan-500/10 hover:text-cyan-400'
                      }`}
                      data-testid={`industry-suggestion-${industry.toLowerCase().replace(/\s+/g, '-')}`}
                    >
                      {industry}
                    </button>
                  ))}
                </motion.div>
              )}
            </div>

            {showNaics && suggestedNaicsTitle && (
              <p className="text-[11px] text-slate-500 leading-tight">
                {suggestedNaicsTitle}
              </p>
            )}
            {errors.industry && <p className="text-cyan-400 text-xs">{errors.industry.message}</p>}
          </div>
        );
      }

      case 'niche_specificity': {
        const industryValue = watchedValues.industry;
        const isGenerating = specStatus === 'loading';
        const hasSuggestion = specStatus === 'suggested' && !!specSuggestion;
        const fieldValue = watchedValues.niche_specificity || '';
        const isAiValue = hasSuggestion && fieldValue === specSuggestion;

        return (
          <div className="space-y-2 w-full">
            {/* Label row */}
            <div className="flex items-center justify-between">
              <GlassLabel htmlFor="niche_specificity">Specialization</GlassLabel>
              {isAiValue && (
                <span className="flex items-center gap-1 text-[11px] font-medium text-cyan-400">
                  <Sparkles size={10} />
                  AI Suggested
                </span>
              )}
            </div>

            {/* Primary input — text, not a dropdown */}
            <Controller
              control={control}
              name="niche_specificity"
              render={({ field }) => (
                <div className="relative">
                  <GlassInput
                    id="niche_specificity"
                    value={field.value}
                    onChange={(e) => {
                      field.onChange(e);
                      // If user starts typing over AI value, clear the "suggested" state
                      if (isAiValue && e.target.value !== specSuggestion) {
                        dismissSpec();
                      }
                    }}
                    placeholder={
                      !industryValue
                        ? "Select your industry first"
                        : isGenerating
                        ? "Analyzing your business…"
                        : "e.g. (what's the main services you offer)"
                    }
                    disabled={!industryValue || isGenerating}
                    data-testid="input-niche-specificity"
                  />
                  {/* Spinner while AI is thinking */}
                  {isGenerating && (
                    <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-1.5">
                      <Loader2 size={13} className="animate-spin text-cyan-400" />
                      <span className="text-[11px] text-cyan-400">Analyzing…</span>
                    </div>
                  )}
                  {/* Clear AI suggestion button */}
                  {isAiValue && (
                    <button
                      type="button"
                      onClick={() => {
                        dismissSpec();
                        field.onChange('');
                      }}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 transition-colors"
                      aria-label="Clear suggestion"
                    >
                      <X size={13} />
                    </button>
                  )}
                </div>
              )}
            />

            {/* Fallback — show when no URL entered OR scrape failed */}
            {showSpecFallback && industryValue && (
              <AnimatePresence>
                {!showManualForm ? (
                  <motion.button
                    key="show-btn"
                    type="button"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    onClick={() => setShowManualForm(true)}
                    className="flex items-center gap-1.5 text-[12px] text-slate-400 hover:text-cyan-400 transition-colors mt-1"
                    data-testid="btn-manual-suggest"
                  >
                    <Wand2 size={12} />
                    Let AI suggest based on what you do
                  </motion.button>
                ) : (
                  <motion.div
                    key="manual-form"
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.2 }}
                    className="mt-2 p-3 rounded-xl border border-cyan-500/20 bg-cyan-500/[0.03] space-y-2 overflow-hidden"
                  >
                    <p className="text-[11px] text-slate-400 mb-2">
                      Tell us a bit about your business so AI can suggest the right specialization.
                    </p>
                    <div className="space-y-2">
                      <GlassInput
                        placeholder="What do you specialize in? (e.g. colon hydrotherapy, detox cleanses)"
                        value={manualSpecialty}
                        onChange={(e) => setManualSpecialty(e.target.value)}
                        data-testid="input-manual-specialty"
                      />
                      <GlassInput
                        placeholder="Who's your ideal customer? (e.g. women 30-50 focused on gut health)"
                        value={manualCustomer}
                        onChange={(e) => setManualCustomer(e.target.value)}
                        data-testid="input-manual-customer"
                      />
                    </div>
                    <div className="flex items-center gap-2 pt-1">
                      <button
                        type="button"
                        onClick={() => {
                          generateSpecFromManual(manualSpecialty, manualCustomer);
                          setShowManualForm(false);
                        }}
                        disabled={!manualSpecialty.trim() && !manualCustomer.trim()}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/30 text-cyan-300 text-[12px] font-medium transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                        data-testid="btn-generate-from-manual"
                      >
                        <Sparkles size={11} />
                        Generate Specialization
                      </button>
                      <button
                        type="button"
                        onClick={() => setShowManualForm(false)}
                        className="text-[12px] text-slate-500 hover:text-slate-300 transition-colors"
                      >
                        Cancel
                      </button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            )}

            {errors.niche_specificity && (
              <p className="text-cyan-400 text-xs">{errors.niche_specificity.message}</p>
            )}
          </div>
        );
      }

      case 'team_size':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel htmlFor="team_size">Team Size</GlassLabel>
            <Controller
              control={control}
              name="team_size"
              render={({ field }) => (
                <GlassRadioGroup
                  options={TEAM_SIZE_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={3}
                />
              )}
            />
            {errors.team_size && <p className="text-cyan-400 text-xs">{errors.team_size.message}</p>}
          </div>
        );

      case 'avg_job_value': {
        const indCfg = resolveIndustryConfig(watchedValues.industry, watchedValues.niche_specificity);
        const ajvCfg = indCfg.avgJobValue;
        const jobUnit = indCfg.jobUnit;
        return (
          <div className="space-y-4 w-full">
            <div className="flex justify-between items-center">
              <GlassLabel htmlFor="avg_job_value">
                Average {jobUnit.charAt(0).toUpperCase() + jobUnit.slice(1)} Value
              </GlassLabel>
              <span className={`font-mono font-medium ${watchedValues.avg_job_value ? 'text-cyan-400' : 'text-slate-500'}`}>
                {watchedValues.avg_job_value
                  ? `$${parseInt(watchedValues.avg_job_value).toLocaleString()}${parseInt(watchedValues.avg_job_value) >= ajvCfg.max ? '+' : ''}`
                  : "Slide to set"}
              </span>
            </div>
            <Controller
              control={control}
              name="avg_job_value"
              render={({ field: sliderField }) => {
                const val = sliderField.value ? parseInt(sliderField.value) : ajvCfg.default;
                return (
                  <GlassSlider
                    min={ajvCfg.min}
                    max={ajvCfg.max}
                    step={ajvCfg.step}
                    value={[val]}
                    onValueChange={(vals) => sliderField.onChange(vals[0].toString())}
                  />
                );
              }}
            />
            <div className="flex justify-between text-[10px] text-slate-600">
              <span>${ajvCfg.min.toLocaleString()}</span>
              <span>${ajvCfg.max.toLocaleString()}+</span>
            </div>
            {errors.avg_job_value && <p className="text-cyan-400 text-xs">{errors.avg_job_value.message}</p>}
          </div>
        );
      }

      case 'monthly_sales_volume': {
        const indCfg2 = resolveIndustryConfig(watchedValues.industry, watchedValues.niche_specificity);
        const msvCfg = indCfg2.monthlyJobs;
        const jobUnit2 = indCfg2.jobUnit;
        return (
          <div className="space-y-4 w-full">
            <div className="flex justify-between items-center">
              <GlassLabel htmlFor="monthly_sales_volume">
                Monthly {jobUnit2.charAt(0).toUpperCase() + jobUnit2.slice(1)}s Completed
              </GlassLabel>
              <span className={`font-mono font-medium ${watchedValues.monthly_sales_volume ? 'text-cyan-400' : 'text-slate-500'}`}>
                {watchedValues.monthly_sales_volume
                  ? `${parseInt(watchedValues.monthly_sales_volume)} ${jobUnit2}s/mo`
                  : "Slide to set"}
              </span>
            </div>
            <Controller
              control={control}
              name="monthly_sales_volume"
              render={({ field: sliderField }) => {
                const val = sliderField.value ? parseInt(sliderField.value) : msvCfg.default;
                return (
                  <GlassSlider
                    min={msvCfg.min}
                    max={msvCfg.max}
                    step={msvCfg.step}
                    value={[val]}
                    onValueChange={(vals) => sliderField.onChange(vals[0].toString())}
                  />
                );
              }}
            />
            <div className="flex justify-between text-[10px] text-slate-600">
              <span>{msvCfg.min} {jobUnit2}s/mo</span>
              <span>{msvCfg.max}+ {jobUnit2}s/mo</span>
            </div>
            <p className="text-xs text-slate-500">Total completed {jobUnit2}s or contracts per month</p>
            {errors.monthly_sales_volume && <p className="text-cyan-400 text-xs">{errors.monthly_sales_volume.message}</p>}
          </div>
        );
      }

      case 'ad_spend': {
        const indCfg3 = resolveIndustryConfig(watchedValues.industry, watchedValues.niche_specificity);
        const asCfg = indCfg3.adSpend;
        return (
          <div className="space-y-4 w-full">
            <div className="flex justify-between items-center">
              <GlassLabel htmlFor="ad_spend">Monthly Ad Spend</GlassLabel>
              <span className={`font-mono font-medium ${watchedValues.ad_spend ? 'text-cyan-400' : 'text-slate-500'}`}>
                {watchedValues.ad_spend
                  ? parseInt(watchedValues.ad_spend) === 0
                    ? '$0 / organic only'
                    : `$${parseInt(watchedValues.ad_spend).toLocaleString()}${parseInt(watchedValues.ad_spend) >= asCfg.max ? '+' : '/mo'}`
                  : "Slide to set"}
              </span>
            </div>
            <Controller
              control={control}
              name="ad_spend"
              render={({ field: sliderField }) => {
                const val = sliderField.value !== undefined ? parseInt(sliderField.value) : 0;
                return (
                  <GlassSlider
                    min={0}
                    max={asCfg.max}
                    step={asCfg.step}
                    value={[val]}
                    onValueChange={(vals) => sliderField.onChange(vals[0].toString())}
                  />
                );
              }}
            />
            <div className="flex justify-between text-[10px] text-slate-600">
              <span>$0 organic</span>
              <span>${asCfg.max.toLocaleString()}+/mo</span>
            </div>
            <p className="text-xs text-slate-500">Google Ads, Meta, LSA, etc. — slide to $0 if running on referrals/organic only</p>
            {errors.ad_spend && <p className="text-cyan-400 text-xs">{errors.ad_spend.message}</p>}
          </div>
        );
      }

      case 'monthly_lead_volume': {
        const indCfg4 = resolveIndustryConfig(watchedValues.industry, watchedValues.niche_specificity);
        const mlvCfg = indCfg4.monthlyLeads;
        const jobUnit4 = indCfg4.jobUnit;
        return (
          <div className="space-y-4 w-full">
            <div className="flex justify-between items-center">
              <GlassLabel htmlFor="monthly_lead_volume">Monthly Leads / Inquiries</GlassLabel>
              <span className={`font-mono font-medium ${watchedValues.monthly_lead_volume ? 'text-cyan-400' : 'text-slate-500'}`}>
                {watchedValues.monthly_lead_volume
                  ? /^\d+$/.test(watchedValues.monthly_lead_volume.trim())
                    ? `${watchedValues.monthly_lead_volume} leads/mo`
                    : watchedValues.monthly_lead_volume
                  : "Slide to set"}
              </span>
            </div>
            <Controller
              control={control}
              name="monthly_lead_volume"
              render={({ field: sliderField }) => {
                const rawVal = sliderField.value ?? "";
                const val = /^\d+$/.test(rawVal.trim()) ? parseInt(rawVal) : mlvCfg.default;
                return (
                  <GlassSlider
                    min={mlvCfg.min}
                    max={mlvCfg.max}
                    step={mlvCfg.step}
                    value={[val]}
                    onValueChange={(vals) => sliderField.onChange(vals[0].toString())}
                  />
                );
              }}
            />
            <div className="flex justify-between text-[10px] text-slate-600">
              <span>{mlvCfg.min} lead/mo</span>
              <span>{mlvCfg.max}+ leads/mo</span>
            </div>
            <p className="text-xs text-slate-500">
              All new inbound inquiries — calls, forms, texts, DMs — before qualification
            </p>
            {errors.monthly_lead_volume && <p className="text-cyan-400 text-xs">{errors.monthly_lead_volume.message}</p>}
          </div>
        );
      }

      case 'first_contact_speed':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">How fast do you typically make first contact with new leads?</GlassLabel>
            <Controller
              control={control}
              name="first_contact_speed"
              render={({ field }) => (
                <GlassRadioGroup
                  options={FIRST_CONTACT_SPEED_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.first_contact_speed && <p className="text-cyan-400 text-xs">{errors.first_contact_speed.message}</p>}
          </div>
        );

      case 'lead_unavailability':
        return (
          <div className="space-y-3 w-full pt-4">
            <GlassLabel className="text-cyan-400 font-bold">How often are leads trying to reach you when no one's available?</GlassLabel>
            <p className="text-xs text-slate-500 mb-2">Think about after-hours, weekends, busy periods, team in the field, etc.</p>
            <Controller
              control={control}
              name="lead_unavailability"
              render={({ field }) => (
                <GlassRadioGroup
                  options={LEAD_UNAVAILABILITY_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.lead_unavailability && <p className="text-cyan-400 text-xs">{errors.lead_unavailability.message}</p>}
          </div>
        );

      case 'phone_unavailable_handling':
        return (
          <div className="space-y-4 w-full">
            <GlassLabel className="text-cyan-400 font-bold">When a phone call comes in and you can't answer, what happens?</GlassLabel>
            <Controller
              control={control}
              name="phone_unavailable_handling"
              render={({ field }) => (
                <VisualCardSelector
                  options={PHONE_UNAVAILABLE_HANDLING_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value, 
                    subtitle: opt.subtitle 
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={2}
                />
              )}
            />
            {errors.phone_unavailable_handling && <p className="text-cyan-400 text-xs">{errors.phone_unavailable_handling.message}</p>}
          </div>
        );

      case 'digital_unavailable_handling':
        return (
          <div className="space-y-4 w-full">
            <GlassLabel className="text-cyan-400 font-bold">When a text, email, or web form comes in and you're busy, what happens?</GlassLabel>
            <Controller
              control={control}
              name="digital_unavailable_handling"
              render={({ field }) => (
                <VisualCardSelector
                  options={DIGITAL_UNAVAILABLE_HANDLING_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value, 
                    subtitle: opt.subtitle 
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={2}
                />
              )}
            />
            {errors.digital_unavailable_handling && <p className="text-cyan-400 text-xs">{errors.digital_unavailable_handling.message}</p>}
          </div>
        );

      case 'no_show_recovery':
        const isAppointmentBased = ['Legal', 'Med Spa / Aesthetics', 'Real Estate', 'Other'].includes(watchedValues.industry || '');
        const label = isAppointmentBased 
          ? "Do you systematically follow up with no-shows to rebook them?"
          : "Do you follow up when customers cancel or aren't home?";
        
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">{label}</GlassLabel>
            <Controller
              control={control}
              name="no_show_recovery"
              render={({ field }) => (
                <GlassRadioGroup
                  options={NO_SHOW_RECOVERY_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.no_show_recovery && <p className="text-cyan-400 text-xs">{errors.no_show_recovery.message}</p>}
          </div>
        );

      case 'quote_followup':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">What happens to quotes that don't close immediately?</GlassLabel>
            <Controller
              control={control}
              name="quote_followup"
              render={({ field }) => (
                <GlassRadioGroup
                  options={QUOTE_FOLLOWUP_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.quote_followup && <p className="text-cyan-400 text-xs">{errors.quote_followup.message}</p>}
          </div>
        );

      case 'dormant_leads': {
        const dormantVal = watchedValues.dormant_leads ?? "";
        const dormantNum = /^\d+$/.test(dormantVal.trim()) ? parseInt(dormantVal) : 150;
        return (
          <div className="space-y-4 w-full pt-4">
            <div className="flex justify-between items-center">
              <GlassLabel className="text-cyan-400 font-bold">
                Dormant contacts sitting in your database (6+ months cold)
              </GlassLabel>
              <span className={`font-mono font-medium text-sm ${dormantVal ? 'text-cyan-400' : 'text-slate-500'}`}>
                {/^\d+$/.test(dormantVal.trim()) ? `${parseInt(dormantVal).toLocaleString()} contacts` : "Slide to set"}
              </span>
            </div>
            <Controller
              control={control}
              name="dormant_leads"
              render={({ field: sliderField }) => {
                const val = /^\d+$/.test((sliderField.value ?? "").trim()) ? parseInt(sliderField.value!) : 150;
                return (
                  <GlassSlider
                    min={0}
                    max={5000}
                    step={25}
                    value={[val]}
                    onValueChange={(vals) => sliderField.onChange(vals[0].toString())}
                  />
                );
              }}
            />
            <div className="flex justify-between text-[10px] text-slate-600">
              <span>0 contacts</span>
              <span>5,000+ contacts</span>
            </div>
            <p className="text-xs text-slate-500">
              Past customers, old quotes, and unresponsive leads — anyone who went cold.
              {dormantNum > 0 && (
                <span className="text-cyan-400/70 ml-1 font-medium">
                  That's ~${Math.round(dormantNum * 0.08).toLocaleString()} in potential DBR revenue at your job value.
                </span>
              )}
            </p>
            {errors.dormant_leads && <p className="text-cyan-400 text-xs">{errors.dormant_leads.message}</p>}
          </div>
        );
      }

      case 'no_show_rate':
        const rateIsAppointmentBased = ['Legal', 'Med Spa / Aesthetics', 'Real Estate', 'Other'].includes(watchedValues.industry || '');
        const rateLabel = rateIsAppointmentBased
          ? "What's your appointment no-show rate?"
          : "What's your average cancellation rate?";

        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">{rateLabel}</GlassLabel>
            <Controller
              control={control}
              name="no_show_rate"
              render={({ field }) => (
                <GlassRadioGroup
                  options={NO_SHOW_RATE_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={2}
                />
              )}
            />
            {errors.no_show_rate && <p className="text-cyan-400 text-xs">{errors.no_show_rate.message}</p>}
          </div>
        );

      case 'contact_channels':
        return (
          <div className="space-y-4 w-full">
            <div className="flex justify-between items-center">
              <GlassLabel className="text-cyan-400 font-bold">How can leads currently contact you?</GlassLabel>
              <span className="text-sm text-slate-500">{(watchedValues.contact_channels || []).length}/8 selected</span>
            </div>
            <p className="text-xs text-slate-500">Select ALL that apply</p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {CONTACT_CHANNEL_OPTIONS.map(option => {
                const isSelected = (watchedValues.contact_channels || []).includes(option.value as ContactChannel);
                return (
                  <button
                    key={option.value}
                    type="button"
                    onClick={() => handleChannelToggle(option.value as ContactChannel)}
                    className={`flex flex-col p-3 rounded-lg border text-center transition-all ${
                      isSelected 
                        ? 'bg-cyan-500/10 border-cyan-500' 
                        : 'bg-slate-900/40 border-slate-700/50 hover:bg-slate-800/60'
                    }`}
                  >
                    <span className={`text-sm font-medium ${isSelected ? 'text-white' : 'text-slate-300'}`}>{option.value}</span>
                    <span className="text-xs text-slate-500 mt-1">{option.subtitle}</span>
                  </button>
                );
              })}
            </div>
            {errors.contact_channels && <p className="text-cyan-400 text-xs">{errors.contact_channels.message}</p>}
          </div>
        );

      case 'ai_search_frequency':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">When people ask AI tools like ChatGPT or Google AI for a recommendation in your industry, does your business come up?</GlassLabel>
            <Controller
              control={control}
              name="ai_search_frequency"
              render={({ field }) => (
                <GlassRadioGroup
                  options={AI_SEARCH_FREQUENCY_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.ai_search_frequency && <p className="text-cyan-400 text-xs">{errors.ai_search_frequency.message}</p>}
          </div>
        );

      case 'ai_readiness':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">Have you done anything to help AI tools find and recommend your business?</GlassLabel>
            <Controller
              control={control}
              name="ai_readiness"
              render={({ field }) => (
                <GlassRadioGroup
                  options={AI_READINESS_OPTIONS.map(opt => ({ value: opt.value, label: opt.value }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.ai_readiness && <p className="text-cyan-400 text-xs">{errors.ai_readiness.message}</p>}
          </div>
        );

      case 'has_automations':
        return (
          <div className="space-y-4 w-full">
            <GlassLabel className="text-cyan-400 font-bold">Do you have automated workflows handling leads or follow-ups?</GlassLabel>
            <Controller
              control={control}
              name="has_automations"
              render={({ field }) => (
                <VisualCardSelector
                  options={HAS_AUTOMATIONS_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value,
                    subtitle: opt.subtitle
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.has_automations && <p className="text-cyan-400 text-xs">{errors.has_automations.message}</p>}
          </div>
        );

      case 'has_ai_intent':
        return (
          <div className="space-y-4 w-full pt-4">
            <div className="text-xs font-bold tracking-[0.2em] text-cyan-400 uppercase mb-2 text-center md:text-left">AI LEAD HANDLING</div>
            <GlassLabel className="text-cyan-400 font-bold">Are you using any AI tools to route, qualify, or respond to inbound leads?</GlassLabel>
            <Controller
              control={control}
              name="has_ai_intent"
              render={({ field }) => (
                <VisualCardSelector
                  options={HAS_AI_INTENT_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value,
                    subtitle: opt.subtitle
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.has_ai_intent && <p className="text-cyan-400 text-xs">{errors.has_ai_intent.message}</p>}
          </div>
        );

      case 'intake_centralization':
        return (
          <div className="space-y-4 w-full">
            <div className="text-xs font-bold tracking-[0.2em] text-cyan-400 uppercase mb-2 text-center md:text-left">CAPTURE ARCHITECTURE</div>
            <GlassLabel className="text-cyan-400 font-bold">How are new leads currently captured?</GlassLabel>
            <Controller
              control={control}
              name="intake_centralization"
              render={({ field }) => (
                <VisualCardSelector
                  options={INTAKE_CENTRALIZATION_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.intake_centralization && <p className="text-cyan-400 text-xs">{errors.intake_centralization.message}</p>}
          </div>
        );

      case 'pipeline_tracking':
        return (
          <div className="space-y-4 w-full">
            <div className="text-xs font-bold tracking-[0.2em] text-cyan-400 uppercase mb-2 text-center md:text-left">CONVERSION PIPELINE</div>
            <GlassLabel className="text-cyan-400 font-bold">Do you track your active pipeline/quotes systematically?</GlassLabel>
            <Controller
              control={control}
              name="pipeline_tracking"
              render={({ field }) => (
                <VisualCardSelector
                  options={PIPELINE_TRACKING_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.pipeline_tracking && <p className="text-cyan-400 text-xs">{errors.pipeline_tracking.message}</p>}
          </div>
        );

      case 'review_request':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">Do you systematically ask every customer for a review?</GlassLabel>
            <Controller
              control={control}
              name="review_request"
              render={({ field }) => (
                <GlassRadioGroup
                  options={REVIEW_REQUEST_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={2}
                />
              )}
            />
            {errors.review_request && <p className="text-cyan-400 text-xs">{errors.review_request.message}</p>}
          </div>
        );

      case 'close_rate': {
        const crVal = watchedValues.close_rate ?? "";
        const crNum = /^\d+$/.test(crVal.trim()) ? parseInt(crVal) : 35;
        const crLabel = crNum <= 20 ? "Below average" : crNum <= 40 ? "Average" : crNum <= 60 ? "Good" : crNum <= 80 ? "Strong" : "Exceptional";
        const crColor = crNum <= 20 ? "text-red-400" : crNum <= 40 ? "text-amber-400" : crNum <= 60 ? "text-cyan-400" : "text-emerald-400";
        return (
          <div className="space-y-4 w-full">
            <GlassLabel className="text-cyan-400 font-bold">
              Out of every 10 leads, how many become paying customers?
            </GlassLabel>
            <div className="flex items-center justify-between">
              <span className="text-slate-400 text-sm">Close rate</span>
              <span className={`font-mono font-bold text-lg ${crColor}`}>
                {/^\d+$/.test(crVal.trim()) ? `${crVal}%` : "—"}
                {/^\d+$/.test(crVal.trim()) && (
                  <span className={`text-xs font-normal ml-2 ${crColor}`}>{crLabel}</span>
                )}
              </span>
            </div>
            <Controller
              control={control}
              name="close_rate"
              render={({ field: sliderField }) => {
                const val = /^\d+$/.test((sliderField.value ?? "").trim()) ? parseInt(sliderField.value!) : 35;
                return (
                  <GlassSlider
                    min={5}
                    max={100}
                    step={5}
                    value={[val]}
                    onValueChange={(vals) => sliderField.onChange(vals[0].toString())}
                  />
                );
              }}
            />
            <div className="flex justify-between text-[10px] text-slate-600">
              <span>5% (1 in 20)</span>
              <span>50% (1 in 2)</span>
              <span>100% (close all)</span>
            </div>
            <p className="text-xs text-slate-500">Ballpark is fine — this directly shapes your revenue gap calculation.</p>
            {errors.close_rate && <p className="text-cyan-400 text-xs">{errors.close_rate.message}</p>}
          </div>
        );
      }

      case 'manual_hours':
        return (
          <div className="space-y-3 w-full">
            <GlassLabel className="text-cyan-400 font-bold">How many hours per week does your team spend on manual follow-up, scheduling, and admin?</GlassLabel>
            <Controller
              control={control}
              name="manual_hours"
              render={({ field }) => (
                <GlassRadioGroup
                  options={MANUAL_HOURS_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={2}
                />
              )}
            />
            {errors.manual_hours && <p className="text-cyan-400 text-xs">{errors.manual_hours.message}</p>}
          </div>
        );

      case 'staff_repeat_questions':
        return (
          <div className="space-y-3 w-full pt-4">
            <div className="text-xs font-bold tracking-[0.2em] text-cyan-400 uppercase mb-2 text-center md:text-left">OPERATIONAL DRAG</div>
            <GlassLabel className="text-cyan-400 font-bold">How often do staff get interrupted by the same customer questions repeatedly?</GlassLabel>
            <Controller
              control={control}
              name="staff_repeat_questions"
              render={({ field }) => (
                <GlassRadioGroup
                  options={STAFF_REPEAT_QUESTIONS_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.staff_repeat_questions && <p className="text-cyan-400 text-xs">{errors.staff_repeat_questions.message}</p>}
          </div>
        );

      case 'process_documentation':
        return (
          <div className="space-y-3 w-full pt-4">
            <div className="text-xs font-bold tracking-[0.2em] text-cyan-400 uppercase mb-2 text-center md:text-left">OPERATIONAL DRAG</div>
            <GlassLabel className="text-cyan-400 font-bold">How well documented are your core business processes (SOPs, scripts, workflows)?</GlassLabel>
            <Controller
              control={control}
              name="process_documentation"
              render={({ field }) => (
                <GlassRadioGroup
                  options={PROCESS_DOCUMENTATION_OPTIONS.map(opt => ({ value: opt, label: opt }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.process_documentation && <p className="text-cyan-400 text-xs">{errors.process_documentation.message}</p>}
          </div>
        );

      case 'operational_complexity':
        return (
          <div className="space-y-4 w-full">
            <div className="text-xs font-bold tracking-[0.2em] text-cyan-400 uppercase mb-2 text-center md:text-left">OPERATIONAL DRAG</div>
            <GlassLabel className="text-cyan-400 font-bold">How complex are your operations?</GlassLabel>
            <Controller
              control={control}
              name="operational_complexity"
              render={({ field }) => (
                <VisualCardSelector
                  options={OPERATIONAL_COMPLEXITY_OPTIONS.map(opt => ({ 
                    value: opt.value, 
                    label: opt.value
                  }))}
                  value={field.value}
                  onChange={field.onChange}
                  columns={1}
                />
              )}
            />
            {errors.operational_complexity && <p className="text-cyan-400 text-xs">{errors.operational_complexity.message}</p>}
          </div>
        );

      case 'contact_first_name':
        return (
          <div className="space-y-4 w-full">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <GlassLabel htmlFor="contact_first_name">First Name</GlassLabel>
                <GlassInput 
                  id="contact_first_name" 
                  placeholder="Jane" 
                  {...register('contact_first_name')} 
                  data-testid="input-contact-first-name"
                />
                {errors.contact_first_name && <p className="text-cyan-400 text-xs">{errors.contact_first_name.message}</p>}
              </div>
              <div className="space-y-2">
                <GlassLabel htmlFor="contact_last_name">Last Name</GlassLabel>
                <GlassInput 
                  id="contact_last_name" 
                  placeholder="Doe" 
                  {...register('contact_last_name')} 
                  data-testid="input-contact-last-name"
                />
                {errors.contact_last_name && <p className="text-cyan-400 text-xs">{errors.contact_last_name.message}</p>}
              </div>
            </div>
          </div>
        );

      case 'contact_email':
        return (
          <div className="space-y-2 w-full">
            <GlassLabel htmlFor="contact_email">Email Address</GlassLabel>
            <GlassInput 
              id="contact_email" 
              type="email"
              placeholder="john@example.com" 
              {...register('contact_email')} 
              data-testid="input-contact-email"
            />
            {errors.contact_email && <p className="text-cyan-400 text-xs">{errors.contact_email.message}</p>}
          </div>
        );

      case 'contact_phone':
        return (
          <div className="space-y-2 w-full">
            <GlassLabel htmlFor="contact_phone">Cell Phone Number (Optional)</GlassLabel>
            <GlassInput 
              id="contact_phone" 
              type="tel"
              placeholder="(555) 000-0000" 
              {...register('contact_phone')} 
              data-testid="input-contact-phone"
            />
          </div>
        );

      case 'disclaimer_accepted':
        return (
          <div className="space-y-4 w-full pt-4">
            <div className="flex items-start gap-3 p-4 rounded-lg bg-slate-900/60 border border-slate-800">
              <input 
                type="checkbox" 
                id="disclaimer_accepted"
                {...register('disclaimer_accepted')}
                className="mt-1 h-4 w-4 rounded border-slate-700 bg-slate-800 text-cyan-500 focus:ring-cyan-500"
              />
              <label htmlFor="disclaimer_accepted" className="text-xs text-slate-400 leading-relaxed cursor-pointer">I understand that these estimates are conservative benchmarks based on industry data. By submitting, I agree to receive my report and related business insights via email.</label>
            </div>
            {errors.disclaimer_accepted && <p className="text-cyan-400 text-xs">{errors.disclaimer_accepted.message}</p>}
          </div>
        );

      default:
        return null;
    }
  };

  /**
   * Step 1 custom render — shows ONLY the Website URL input up front, then
   * progressively reveals the other fields once the scrape has completed (or
   * the user has manually typed anything). Philosophy: if you have a website,
   * we do the work for you. If you don't, we'll ask.
   */
  const renderIdentityStep = () => {
    const hasScrapeResult = scrapeStatus === 'success' && scrapeInsights?.success;
    const hasScrapeError = scrapeStatus === 'error' || (scrapeStatus === 'success' && !scrapeInsights?.success);
    const userHasTypedDetails = !!(
      watchedValues.business_name ||
      watchedValues.industry ||
      watchedValues.niche_specificity
    );
    const showDetails = hasScrapeResult || hasScrapeError || userHasTypedDetails;

    return (
      <>
        {renderField('website_url')}

        <AnimatePresence>
          {showDetails && (
            <motion.div
              key="identity-details"
              initial={{ opacity: 0, y: -6, height: 0 }}
              animate={{ opacity: 1, y: 0, height: 'auto' }}
              exit={{ opacity: 0, y: -6, height: 0 }}
              transition={{ duration: 0.3, ease: 'easeOut' }}
              className="space-y-6 overflow-hidden"
            >
              {/* Prominent adjust-if-needed banner — encourages the user to confirm */}
              {hasScrapeResult && (
                <div className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-900/60 border border-slate-800">
                  <Sparkles size={14} className="text-cyan-400 mt-0.5 shrink-0" />
                  <p className="text-[12px] text-slate-300 leading-relaxed">
                    <span className="text-white font-semibold">We&apos;ve pre-filled everything from your site.</span>{" "}
                    <span className="text-slate-400">Tap any field below to adjust before you continue — you&apos;re in full control.</span>
                  </p>
                </div>
              )}

              {renderField('business_name')}
              {renderField('industry')}
              {renderField('niche_specificity')}
            </motion.div>
          )}
        </AnimatePresence>
      </>
    );
  };

  return (
    <div className="min-h-screen text-foreground font-sans selection:bg-primary/30 relative overflow-hidden bg-background">
      <div className="fixed inset-0 z-0 bg-grid-pattern pointer-events-none" />
      <div className="fixed inset-0 z-0 bg-gradient-to-b from-background via-transparent to-background pointer-events-none" />
      
      <header className="fixed top-0 left-0 right-0 z-50 h-20 glass-panel flex items-center px-6 md:px-12 justify-between">
        <Link href="/">
          <div className="text-xl font-heading font-bold tracking-tighter hover:opacity-80 transition-opacity flex items-center gap-3 cursor-pointer">
            <div className="w-3 h-3 rounded-full bg-cyan-400 shadow-[0_0_10px_rgba(34,211,238,0.8)]" />
            <span className="text-white text-lg tracking-wide">SimpleSequence</span>
          </div>
        </Link>
        
        <Link 
          href="/"
          className="flex items-center gap-2 text-sm text-[#6b7280] hover:text-[#00D9FF] transition-colors" 
          data-testid="link-back-to-main-site"
        >
          <span className="hidden md:inline">Back to Main Site</span>
          <ExternalLink size={16} />
        </Link>
      </header>

      <main className="relative z-10 pt-32 pb-12 px-4 md:px-8 max-w-2xl mx-auto min-h-[calc(100vh-80px)] flex flex-col">
        <div className="mb-8">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium text-cyan-400">
              {currentStepIndex === STEPS.length - 1 ? '100' : currentStep.progress}% Complete
            </span>
            <span className="text-sm font-semibold text-white">
              {currentStep.title}
            </span>
          </div>
          <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden mb-3">
            <motion.div
              className="h-full bg-gradient-to-r from-cyan-500 to-cyan-400"
              initial={{ width: 0 }}
              animate={{ width: `${currentStepIndex === STEPS.length - 1 ? 100 : currentStep.progress}%` }}
              transition={{ duration: 0.3 }}
            />
          </div>
          {/* Section label pills */}
          <div className="flex gap-1.5 flex-wrap">
            {STEPS.map((step, i) => {
              const isActive = i === currentStepIndex;
              const isDone = i < currentStepIndex;
              const shortLabels: Record<string, string> = {
                identity: 'Business',
                numbers: 'Numbers',
                pain: 'Pain',
                'capture-speed': 'Speed',
                'capture-ai': 'AI Discovery',
                convert: 'Convert',
                compound: 'Compound',
                automation: 'Automation',
                operations: 'Operations',
                contact: 'Results',
              };
              return (
                <span
                  key={step.id}
                  className="text-[10px] px-2 py-0.5 rounded-full font-medium transition-all"
                  style={{
                    backgroundColor: isActive ? 'rgba(34,211,238,0.15)' : isDone ? 'rgba(34,211,238,0.06)' : 'rgba(30,41,59,0.5)',
                    color: isActive ? '#22d3ee' : isDone ? '#0891b2' : '#475569',
                    border: isActive ? '1px solid rgba(34,211,238,0.4)' : '1px solid transparent',
                  }}
                >
                  {isDone ? '✓ ' : ''}{shortLabels[step.id] ?? step.title}
                </span>
              );
            })}
          </div>
        </div>

        <AnimatePresence mode="wait">
          <motion.div
            key={currentStep.id}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <GlassCard className="p-8">
              <div className="mb-8">
                {isStep3 && (
                  <span className="text-[10px] font-bold tracking-[0.2em] text-cyan-400 uppercase block mb-2">
                    DIAGNOSTIC CALIBRATION
                  </span>
                )}
                <h2 className="text-2xl md:text-3xl font-heading font-bold text-white mb-3">
                  {currentStep.title}
                </h2>
                <p className="text-slate-400 text-sm md:text-base leading-relaxed">
                  {currentStep.description}
                </p>
              </div>

              <div className="space-y-6">
                {currentStep.id === "identity"
                  ? renderIdentityStep()
                  : currentStep.fields.map(field => (
                      <div key={field}>{renderField(field)}</div>
                    ))}
              </div>

              <div className="flex justify-between mt-8 pt-6 border-t border-slate-700/50">
                <GlassButton
                  type="button"
                  variant="ghost"
                  onClick={handleBack}
                  disabled={currentStepIndex === 0}
                  data-testid="button-back"
                >
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  Back
                </GlassButton>
                <GlassButton
                  type="button"
                  onClick={handleNext}
                  disabled={isSubmitting}
                  data-testid="button-next"
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Analyzing...
                    </>
                  ) : currentStepIndex === STEPS.length - 1 ? (
                    <>
                      Get Results
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </>
                  ) : (
                    <>
                      Continue
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </>
                  )}
                </GlassButton>
              </div>
            </GlassCard>
          </motion.div>
        </AnimatePresence>
      </main>
    </div>
  );
}
